<?php
return[
    [
        'dish_id'=>1,
        'order_id'=>1,
        'amount'=>2
    ],[
        'dish_id'=>2,
        'order_id'=>1,
        'amount'=>3
    ],[
        'dish_id'=>3,
        'order_id'=>1,
        'amount'=>3
    ],[
        'dish_id'=>4,
        'order_id'=>1,
        'amount'=>2
        //!================
    ],[
        'dish_id'=>1,
        'order_id'=>2,
        'amount'=>2
    ],[
        'dish_id'=>2,
        'order_id'=>2,
        'amount'=>2
    ],[
        'dish_id'=>3,
        'order_id'=>2,
        'amount'=>2
    ],[
        'dish_id'=>5,
        'order_id'=>2,
        'amount'=>2
        //!================
    ],[
        'dish_id'=>2,
        'order_id'=>3,
        'amount'=>2
    ],[
        'dish_id'=>5,
        'order_id'=>3,
        'amount'=>2
    ],[
        'dish_id'=>4,
        'order_id'=>3,
        'amount'=>2
        //!================
    ],[
        'dish_id'=>6,
        'order_id'=>4,
        'amount'=>2
    ],[
        'dish_id'=>7,
        'order_id'=>4,
        'amount'=>2
    ],[
        'dish_id'=>8,
        'order_id'=>4,
        'amount'=>2
        //!================
    ],[
        'dish_id'=>6,
        'order_id'=>5,
        'amount'=>2
    ],[
        'dish_id'=>9,
        'order_id'=>5,
        'amount'=>2
    ],[
        'dish_id'=>10,
        'order_id'=>5,
        'amount'=>1
        //!================
    ],[
        'dish_id'=>11,
        'order_id'=>6,
        'amount'=>1
    ],[
        'dish_id'=>12,
        'order_id'=>6,
        'amount'=>2
    ],[
        'dish_id'=>13,
        'order_id'=>6,
        'amount'=>2
    ],[
        'dish_id'=>14,
        'order_id'=>6,
        'amount'=>1
        //!================
    ],[
        'dish_id'=>16,
        'order_id'=>7,
        'amount'=>1
    ],[
        'dish_id'=>17,
        'order_id'=>7,
        'amount'=>2
    ],[
        'dish_id'=>18,
        'order_id'=>7,
        'amount'=>2
    ],[
        'dish_id'=>19,
        'order_id'=>7,
        'amount'=>2
    ],[
        'dish_id'=>20,
        'order_id'=>7,
        'amount'=>1
        //!================
    ],[
        'dish_id'=>20,
        'order_id'=>8,
        'amount'=>1
    ],[
        'dish_id'=>17,
        'order_id'=>8,
        'amount'=>2
    ],[
        'dish_id'=>19,
        'order_id'=>8,
        'amount'=>2
    ],[
        'dish_id'=>16,
        'order_id'=>8,
        'amount'=>2
    ],[
        'dish_id'=>18,
        'order_id'=>8,
        'amount'=>1
        //!================
    ],[
        'dish_id'=>21,
        'order_id'=>9,
        'amount'=>1
    ],[
        'dish_id'=>22,
        'order_id'=>9,
        'amount'=>2
    ],[
        'dish_id'=>23,
        'order_id'=>9,
        'amount'=>2
    ],[
        'dish_id'=>24,
        'order_id'=>9,
        'amount'=>2
    ],
    //!------------------
    [
        'dish_id'=>21,
        'order_id'=>10,
        'amount'=>2
    ],[
        'dish_id'=>22,
        'order_id'=>10,
        'amount'=>1
    ],[
        'dish_id'=>23,
        'order_id'=>10,
        'amount'=>1
    ],[
        'dish_id'=>24,
        'order_id'=>10,
        'amount'=>2
    ],
    //!------------------
    [
        'dish_id'=>25,
        'order_id'=>11,
        'amount'=>2
    ],[
        'dish_id'=>26,
        'order_id'=>11,
        'amount'=>2
    ],[
        'dish_id'=>27,
        'order_id'=>11,
        'amount'=>2
    ],[
        'dish_id'=>28,
        'order_id'=>11,
        'amount'=>1
    ],
    //!------------------
    [
        'dish_id'=>29,
        'order_id'=>12,
        'amount'=>2
    ],[
        'dish_id'=>30,
        'order_id'=>12,
        'amount'=>2
    ],[
        'dish_id'=>31,
        'order_id'=>12,
        'amount'=>2
    ],[
        'dish_id'=>32,
        'order_id'=>12,
        'amount'=>1
    ],
    //!------------------
    [
        'dish_id'=>35,
        'order_id'=>13,
        'amount'=>2
    ],[
        'dish_id'=>36,
        'order_id'=>13,
        'amount'=>2
    ],[
        'dish_id'=>37,
        'order_id'=>13,
        'amount'=>2
    ],[
        'dish_id'=>38,
        'order_id'=>13,
        'amount'=>1
    ],
    //!------------------
    [
        'dish_id'=>39,
        'order_id'=>14,
        'amount'=>2
    ],[
        'dish_id'=>40,
        'order_id'=>14,
        'amount'=>2
    ],[
        'dish_id'=>41,
        'order_id'=>14,
        'amount'=>2
    ],[
        'dish_id'=>44,
        'order_id'=>14,
        'amount'=>1
    ],
    //!------------------
    [
        'dish_id'=>45,
        'order_id'=>15,
        'amount'=>2
    ],[
        'dish_id'=>46,
        'order_id'=>15,
        'amount'=>2
    ],[
        'dish_id'=>48,
        'order_id'=>15,
        'amount'=>2
    ],[
        'dish_id'=>49,
        'order_id'=>15,
        'amount'=>1
    ],
    //!------------------
    [
        'dish_id'=>50,
        'order_id'=>16,
        'amount'=>2
    ],[
        'dish_id'=>51,
        'order_id'=>16,
        'amount'=>2
    ],[
        'dish_id'=>52,
        'order_id'=>16,
        'amount'=>2
    ],[
        'dish_id'=>54,
        'order_id'=>16,
        'amount'=>1
    ],
    //!------------------
    [
        'dish_id'=>55,
        'order_id'=>17,
        'amount'=>2
    ],[
        'dish_id'=>56,
        'order_id'=>17,
        'amount'=>2
    ],[
        'dish_id'=>57,
        'order_id'=>17,
        'amount'=>2
    ],[
        'dish_id'=>58,
        'order_id'=>17,
        'amount'=>1
    ],
    //!------------------
    [
        'dish_id'=>59,
        'order_id'=>18,
        'amount'=>2
    ],[
        'dish_id'=>60,
        'order_id'=>18,
        'amount'=>2
    ],[
        'dish_id'=>61,
        'order_id'=>18,
        'amount'=>2
    ],[
        'dish_id'=>62,
        'order_id'=>18,
        'amount'=>1
    ],
    //!------------------
    [
        'dish_id'=>63,
        'order_id'=>19,
        'amount'=>3
    ],[
        'dish_id'=>64,
        'order_id'=>19,
        'amount'=>1
    ],[
        'dish_id'=>65,
        'order_id'=>19,
        'amount'=>1
    ],[
        'dish_id'=>67,
        'order_id'=>19,
        'amount'=>1
    ],
    //!------------------
    [
        'dish_id'=>68,
        'order_id'=>20,
        'amount'=>2
    ],[
        'dish_id'=>69,
        'order_id'=>20,
        'amount'=>1
    ],[
        'dish_id'=>71,
        'order_id'=>20,
        'amount'=>4
    ],[
        'dish_id'=>72,
        'order_id'=>20,
        'amount'=>1
    ],
    //!------------------
    [
        'dish_id'=>73,
        'order_id'=>21,
        'amount'=>2
    ],[
        'dish_id'=>74,
        'order_id'=>21,
        'amount'=>1
    ],[
        'dish_id'=>75,
        'order_id'=>21,
        'amount'=>2
    ],
    //!------------------
    [
        'dish_id'=>76,
        'order_id'=>22,
        'amount'=>2
    ],[
        'dish_id'=>77,
        'order_id'=>22,
        'amount'=>1
    ],[
        'dish_id'=>78,
        'order_id'=>22,
        'amount'=>4
    ],[
        'dish_id'=>79,
        'order_id'=>22,
        'amount'=>1
    ],
    //!------------------
    [
        'dish_id'=>80,
        'order_id'=>23,
        'amount'=>2
    ],[
        'dish_id'=>81,
        'order_id'=>23,
        'amount'=>4
    ],[
        'dish_id'=>82,
        'order_id'=>23,
        'amount'=>4
    ],[
        'dish_id'=>83,
        'order_id'=>23,
        'amount'=>1
    ],
    //!------------------
]
?>