<?php
return[
    [
        'dish_id'=>1,
        'order_id'=>1,
        'quantity'=>2
    ],[
        'dish_id'=>1,
        'order_id'=>1,
        'quantity'=>1
    ],[
        'dish_id'=>1,
        'order_id'=>1,
        'quantity'=>3
    ],[
        'dish_id'=>1,
        'order_id'=>1,
        'quantity'=>2
        //!================
    ],[
        'dish_id'=>7,
        'order_id'=>2,
        'quantity'=>2
    ],[
        'dish_id'=>8,
        'order_id'=>2,
        'quantity'=>2
    ],[
        'dish_id'=>9,
        'order_id'=>2,
        'quantity'=>2
    ],[
        'dish_id'=>10,
        'order_id'=>2,
        'quantity'=>2
        //!================
    ],[
        'dish_id'=>10,
        'order_id'=>3,
        'quantity'=>2
    ],[
        'dish_id'=>15,
        'order_id'=>3,
        'quantity'=>2
    ],[
        'dish_id'=>18,
        'order_id'=>3,
        'quantity'=>2
        //!================
    ],[
        'dish_id'=>17,
        'order_id'=>4,
        'quantity'=>2
    ],[
        'dish_id'=>19,
        'order_id'=>4,
        'quantity'=>2
    ],[
        'dish_id'=>20,
        'order_id'=>4,
        'quantity'=>2
        //!================
    ]
]
?>