<?php
return [
    [
        'delivery_address' => 'Via Cobalto 23',
        'customer_name' => 'Pino',
        'customer_surname' => 'Laravella',
        'customer_phone_number' => '1234657890',
        'customer_email' => 'pino.laravella@libero.it',
        'total_price' => '70.00',
        'is_paid' => '1',

    ], [
        'delivery_address' => 'Via Roma 122',
        'customer_name' => 'Francesca',
        'customer_surname' => 'De Angelis',
        'customer_phone_number' => '0212345672',
        'customer_email' => 'francescadeangelis@gmail.com',
        'total_price' => '52.20',
        'is_paid' => 0,

    ], [
        'delivery_address' => 'Via Pompilio 11',
        'customer_name' => 'Luisa',
        'customer_surname' => 'Panettieri',
        'customer_phone_number' => '1234647890',
        'customer_email' => 'luisa.panettieri@yahoo.com',
        'total_price' => '35.10',
        'is_paid' => 1,

    ], [
        'delivery_address' => 'via Baratta 23',
        'customer_name' => 'Marco',
        'customer_surname' => 'Foggia',
        'customer_phone_number' => '1234347890',
        'customer_email' => 'marco.foggia@deliveboo.it',
        'total_price' => '19.90',
        'is_paid' => 1,
    ], [
        'delivery_address' => 'Via Bellini 3',
        'customer_name' => 'Marco',
        'customer_surname' => 'Neri',
        'customer_phone_number' => '0655555550',
        'customer_email' => 'marco_neri@gmail.com',
        'total_price' => '49.90',
        'is_paid' => 1,
    ],[
        'delivery_address' => 'Corso Buenos Aires',
        'customer_name' => 'Luca',
        'customer_surname' => 'Esposito',
        'customer_phone_number' => '0655523450',
        'customer_email' => 'esposito.luchino@yahoo.com',
        'total_price' => '29.90',
        'is_paid' => 1,
    ],[
        'delivery_address' => 'Via Nazionale delle Puglie 88',
        'customer_name' => 'Sara',
        'customer_surname' => 'Rossetti',
        'customer_phone_number' => '0651223450',
        'customer_email' => 'rossetti.sara@yahoo.com',
        'total_price' => '38.70',
        'is_paid' => 1,
    ],[
        'delivery_address' => 'Piazza Castello 4',
        'customer_name' => 'Andrea',
        'customer_surname' => 'Moretti',
        'customer_phone_number' => '1065127350',
        'customer_email' => 'moretti_andrea@libero.com',
        'total_price' => '12.40',
        'is_paid' => 0,
    ],[
        'delivery_address' => 'Via del Corso 45',
        'customer_name' => 'Marina',
        'customer_surname' => 'Rizzo',
        'customer_phone_number' => '1063527350',
        'customer_email' => 'rizzo.marina@libero.com',
        'total_price' => '64.40',
        'is_paid' => 0,
    ],[
        'delivery_address' => 'Corso Umberto I',
        'customer_name' => 'Giuseppe',
        'customer_surname' => 'Russo',
        'customer_phone_number' => '1063767350',
        'customer_email' => 'giuseppe_russo@gmail.com',
        'total_price' => '79.00',
        'is_paid' => 1,
    ],[
        'delivery_address' => 'Via della Spiga 2',
        'customer_name' => 'Laura',
        'customer_surname' => 'Ferrari',
        'customer_phone_number' => '1063767520',
        'customer_email' => 'ferrarilaura@gmail.com',
        'total_price' => '27.00',
        'is_paid' => 1,
    ],[
        'delivery_address' => 'Piazza Navona',
        'customer_name' => 'Alessandro',
        'customer_surname' => 'Vitale',
        'customer_phone_number' => '1063761230',
        'customer_email' => 'vitale.alessandro@gmail.com',
        'total_price' => '88.10',
        'is_paid' => 0,
    ],[
        'delivery_address' => 'Via dei Tribunali 2',
        'customer_name' => 'Valentina',
        'customer_surname' => 'Lombardi',
        'customer_phone_number' => '1036761230',
        'customer_email' => 'valentinalombardi@gmail.com',
        'total_price' => '95.60',
        'is_paid' => 1,
    ],[
        'delivery_address' => 'via del Corso 45',
        'customer_name' => 'Giulia',
        'customer_surname' => 'Verdi',
        'customer_phone_number' => '3478901234',
        'customer_email' => 'giulia.verdi@gmail.com',
        'total_price' => '25.50',
        'is_paid' => 1,
        ],
        [
        'delivery_address' => 'via Roma 12',
        'customer_name' => 'Francesco',
        'customer_surname' => 'Bianchi',
        'customer_phone_number' => '3334567890',
        'customer_email' => 'francesco.bianchi@yahoo.it',
        'total_price' => '45.00',
        'is_paid' => 1,
        ],
        [
        'delivery_address' => 'via Garibaldi 87',
        'customer_name' => 'Simone',
        'customer_surname' => 'Russo',
        'customer_phone_number' => '3456781234',
        'customer_email' => 'simone.russo@libero.it',
        'total_price' => '28.90',
        'is_paid' => 1,
        ],
        [
        'delivery_address' => 'via della Croce 15',
        'customer_name' => 'Carla',
        'customer_surname' => 'Neri',
        'customer_phone_number' => '3389012345',
        'customer_email' => 'carla.neri@gmail.com',
        'total_price' => '35.00',
        'is_paid' => 1,
        ],
        [
        'delivery_address' => 'via XX Settembre 8',
        'customer_name' => 'Luca',
        'customer_surname' => 'Verdi',
        'customer_phone_number' => '3451236789',
        'customer_email' => 'luca.verdi@alice.it',
        'total_price' => '12.90',
        'is_paid' => 1,
        ],
        [
        'delivery_address' => 'piazza del Popolo 4',
        'customer_name' => 'Antonella',
        'customer_surname' => 'Rossi',
        'customer_phone_number' => '3478905678',
        'customer_email' => 'antonella.rossi@hotmail.com',
        'total_price' => '22.50',
        'is_paid' => 1,
        ],
        [
        'delivery_address' => 'via dei Mille 10',
        'customer_name' => 'Giovanni',
        'customer_surname' => 'Ferrari',
        'customer_phone_number' => '3398901234',
        'customer_email' => 'giovanni.ferrari@tiscali.it',
        'total_price' => '19.90',
        'is_paid' => 1,
        ],
        [
        'delivery_address' => 'via Cavour 77',
        'customer_name' => 'Laura',
        'customer_surname' => 'Bianchi',
        'customer_phone_number' => '3494567890',
        'customer_email' => 'laura.bianchi@virgilio.it',
        'total_price' => '15.00',
        'is_paid' => 1,
        ],
        [
        'delivery_address' => 'Via Dante 5',
        'customer_name' => 'Paolo',
        'customer_surname' => 'Verdi',
        'customer_phone_number' => '3456123789',
        'customer_email' => 'paolo.verdi@deliveboo.it',
        'total_price' => '12.90',
        'is_paid' => 1,
        ],
        [
        'delivery_address' => 'Via Garibaldi 8',
        'customer_name' => 'Chiara',
        'customer_surname' => 'Ricci',
        'customer_phone_number' => '3409876543',
        'customer_email' => 'chiara.ricci@deliveboo.it',
        'total_price' => '23.40',
        'is_paid' => 0, 
        ]

];
