<?php 
return [
    [
        'user_id'=>1,
        'address'=>'via Roma 37',
        'name'=>'Gusto Italiano',
        'description'=>'Gusto Italiano è un ristorante italiano tradizionale situato nel cuore della città. Qui, puoi gustare piatti della cucina italiana preparati con ingredienti freschi e di qualità, presentati in modo elegante e raffinato. Il menu propone una vasta selezione di pasta fresca, carne e pesce, accompagnati da vini pregiati e selezionati.',
        'image'=>'upload/pasta-7.jpg',
        'rating'=> '4.8 Molto Buono (+500)',
    ], [
        'user_id'=>2,
        'address'=>'via Milano 32',
        'name'=>'Pizzeria della Nonna',
        'description'=>'La Pizzeria della Nonna è un\'osteria familiare e accogliente che serve pizze cotte nel forno a legna secondo le ricette della tradizione italiana. Qui puoi gustare pizze preparate con ingredienti freschi e genuini, come la mozzarella di bufala, il pomodoro San Marzano e l\'olio extravergine d\'oliva.',
        'image'=>'upload/pizza-8.jpg',
        'rating'=> '4.5 Molto Buono (+500)',
    ],[
        'user_id'=>3,
        'address'=>'via Prione 19',
        'name'=>'Osteria del Buongusto',
        'description'=>'L\'Osteria del Buongusto è un ristorante tipico italiano dove puoi assaporare piatti rustici e genuini della cucina casalinga. Il menu offre una vasta selezione di piatti della tradizione italiana, come la pasta fresca, frittura italiana e dolci tipici.',
        'image'=>'upload/ristorante-italiano-2.jpg',
        'rating'=> '4.2 Molto Buono (+500)',

    ],[
        'user_id'=>4,
        'address'=>'via Gramsci 32',
        'name'=>'Il Montanaro',
        'description'=>' Il Montanaro è un luogo perfetto per gustare piatti di carne e hamburger made in Italy di qualità preparati con cura. Il menu offre una vasta selezione di panini e di carni accompagnati da una carta dei vini ben fornita.',
        'image'=>'upload/hamburger-4.jpg', 
        'rating'=> '4.2 Molto Buono (399)',
    ],[
        'user_id'=>5,
        'address'=>'via Verdi 35',
        'name'=>'La Tavernetta',
        'description'=>'La Tavernetta è un ristorante pizzeria tipico italiano, situato in una vecchia cantina del centro storico. Il menu offre una vasta selezione di piatti della cucina tradizionale italiana. L\'atmosfera calda e accogliente del ristorante rende La Tavernetta il luogo ideale per gustare piatti gustosi in un ambiente familiare.',
        'image'=>'upload/dessert-1.jpg',
        'rating'=> '3.8 Buono (450)',
    ],[
        'user_id'=>6,
        'address'=>'via Gramsci 32',
        'name'=>'Dolce Vita Gelato',
        'description'=>'Dolce Vita Gelato è una gelateria artigianale che offre una vasta gamma di gelati, sorbetti e dessert freschi, preparati con ingredienti naturali e di prima qualità. La gelateria propone una vasta scelta di gusti, dai più classici come la vaniglia e il cioccolato, ai gusti più innovativi come la mela verde e la crema di limoncello.',
        'image'=>'upload/gelateria-1.jpg',
        'rating'=> '3.6 Buono (388)',
    ],[
        'user_id'=>7,
        'address'=>'via Bondi 52',
        'name'=>'Hamburger Lab',
        'description'=>'Hamburger Lab è un ristorante gourmet che propone hamburger di carne di alta qualità, accompagnati da patatine fritte croccanti e salse fatte in casa. Il menu offre una vasta scelta di hamburger, dal classico cheeseburger al burger di agnello con feta e menta. L\'ambiente moderno e accogliente rende il ristorante il luogo perfetto per un pranzo o una cena informale con amici e colleghi.',
        'image'=>'upload/hamburger-2.jpg',
        'rating'=> '3.0 Buono (230)',
    ],[
        'user_id'=>8,
        'address'=>'via Margin 12',
        'name'=>'La Locanda del Borgo',
        'description'=>"Il ristorante basa la sua cucina su carni di primissima qualità e dolci tipici della tradizione. Il menu cambia spesso per riflettere le specialità stagionali. L'atmosfera è accogliente e familiare, e il personale ti farà sentire a casa.",
        'image'=>'upload/meat-11.jpg',
        'rating'=> '4.2 Molto Buono (266)',
    ],[
        'user_id'=>9,
        'address'=>'via Cobalto 11',
        'name'=>'Il Gelato Artigianale',
        'description'=>"Nel nostro locale l'arte della gelateria è presa molto seriamente. Qui il gelato viene preparato con ingredienti freschi e di alta qualità, senza l'aggiunta di conservanti o coloranti. Potrai scegliere tra una vasta selezione di gusti, dal classico cioccolato alla fragola, fino a quelli più insoliti come il basilico o il limone al pepe nero. Inoltre, potrai gustare i sorbetti freschi e leggeri, ideali per una pausa rinfrescante in una calda giornata estiva.",
        'image'=>'upload/dessert-15.jpg',
        'rating'=> '4.9 Molto Buono (99)',
    ],[
        'user_id'=>10,
        'address'=>'via Montessori 2',
        'name'=>'Karma Sushi',
        'description'=>"Karma Sushi è un ristorante giapponese offre un'ampia scelta di piatti di sushi, sashimi e tempura. Il pesce fresco e di alta qualità è la base della cucina, e viene accompagnato da ingredienti freschi e di stagione. Il menu è ricco di opzioni vegetariane e senza glutine, così come di piatti per i palati più avventurosi. L'ambiente è moderno e accogliente, e il personale è sempre disponibile a consigliarti i migliori piatti da provare.",
        'image'=>'upload/sushi-9.jpg',
        'rating'=> '3.5 Buono (320)',
    ],[
        'user_id'=>11,
        'address'=>'via Paolo Borsellino 1',
        'name'=>'Wok to Walk',
        'description'=>"Se sei alla ricerca di cibo asiatico veloce e sano, Wok to Walk è il posto giusto per te. Qui potrai gustare piatti wok freschi e personalizzati, preparati davanti ai tuoi occhi con ingredienti di qualità e una vasta scelta di salse. Il menu offre una grande varietà di opzioni vegetariane e vegane, così come di piatti di carne e pesce. L'atmosfera è informale e accogliente, perfetta per una pausa pranzo veloce o una cena informale con gli amici.",
        'image'=>'upload/sushi-6.jpg',
        'rating'=> '3.5 Buono (320)',
    ],[
        'user_id'=>12,
        'address'=>'via Maranza 13',
        'name'=>'Sushi Zen',
        'description'=>"Offriamo piatti di sushi freschi e di alta qualità, preparati con pesce di stagione e accompagnati da riso perfettamente cotto. Il menu offre una vasta scelta di opzioni di sushi, dal classico nigiri al sushi a rotoli. Inoltre, potrai gustare anche piatti di tempura e di carne o pesce alla griglia. L'atmosfera è rilassante e accogliente, perfetta per una cena romantica o una serata con gli amici.",
        'image'=>'upload/sushi-10.jpg',
        'rating'=> '3.5 Buono (320)',
    ],[
        'user_id'=>13,
        'address'=>'via dei Gigli 10',
        'name'=>'Sushi Samba',
        'description'=>"Ristorante fusion giapponese-brasiliano che offre una cucina unica e sorprendente. Qui potrai gustare piatti di sushi creativi e innovativi, preparati con pesce fresco e ingredienti di stagione. Inoltre, il menu offre anche una vasta scelta di piatti brasiliani, come il feijoada e la moqueca.",
        'image'=>'upload/sushi-7.jpg',
        'rating'=> '3.5 Buono (320)',
    ],[
        'user_id'=>14,
        'address'=>'via Marconi 1',
        'name'=>'Asia Timezone',
        'description'=>"Un ristorante che offre una vasta scelta di piatti asiatici provenienti da diverse regioni del continente. I clienti possono gustare specialità tailandesi, cinesi, giapponesi e coreane, tra cui sushi, ramen, pad thai, bulgogi e molti altri piatti tipici. L'atmosfera del ristorante è moderna e accogliente, con un'attenzione particolare all'estetica e alla presentazione dei piatti. Il personale è sempre disponibile a dare consigli e suggerimenti sulla scelta dei piatti e sulle combinazioni di sapori.",
        'image'=>'upload/ristorante-sushi-2.jpg',
        'rating'=> '3.5 Buono (320)',
    ],[
        'user_id'=>15,
        'address'=>'via Gioberti 16',
        'name'=>'Wasabi Mami',
        'description'=>"Un ristorante giapponese che offre sushi, sashimi e altre specialità della cucina giapponese preparate con ingredienti freschi e di alta qualità. Il menu presenta una vasta scelta di piatti per accontentare tutti i gusti, compresi piatti vegetariani e vegani. L'ambiente è moderno e accogliente, con un'attenzione particolare ai dettagli. Il personale è sempre disponibile a dare consigli sui piatti e sulla scelta del sake giusto da abbinare ai piatti.",
        'image'=>'upload/ristorante-sushi-1.jpg',
        'rating'=> '3.5 Buono (320)',
    ],[
        'user_id'=>16,
        'address'=>'Pzz. Garibaldi 6',
        'name'=>'Sushi Express',
        'description'=>"Cucina giapponese, piatti preparati al momento per garantire la massima freschezza. Il menu presenta una vasta scelta di piatti per accontentare tutti i gusti, compresi piatti vegetariani e vegani. Il ristorante è caratterizzato da un'atmosfera accogliente e informale, ideale per una cena veloce o un pranzo in pausa pranzo. Il personale è sempre disponibile a dare consigli sui piatti e sui condimenti giusti da abbinare ai piatti.",
        'image'=>'upload/ristorante-sushi-3.jpg',
        'rating'=> '3.5 Buono (320)',
    ],[
        'user_id'=>17,
        'address'=>'via Vittorio Emanuele II',
        'name'=>'Hello China',
        'description'=>"Un ristorante cinese che offre una vasta scelta di piatti della cucina cinese, tra cui i classici come il pollo agrodolce e il maiale in salsa di soia, insieme a piatti più insoliti come il tofu piccante e le verdure saltate. L'ambiente del ristorante è caratterizzato da arredamenti tipici cinesi e l'atmosfera è accogliente e informale. Il personale è sempre disponibile a dare consigli sui piatti e sulle combinazioni di sapori.",
        'image'=>'upload/sushi-4.jpg',
        'rating'=> '3.5 Buono (320)',
    ],[
        'user_id'=>18,
        'address'=>'via Foscolo 7',
        'name'=>'Asian Garden',
        'description'=>"Un ristorante asiatico che offre una vasta scelta di piatti provenienti da diverse regioni dell'Asia, tra cui sushi, ramen, pad thai, bibimbap e molti altri piatti tipici. L'ambiente del ristorante è caratterizzato da una fusione di arredamenti tipici di diverse culture asiatiche, creando un'atmosfera unica e suggestiva. Il personale è sempre disponibile a dare consigli sui piatti e sulle combinazioni di sapori.",
        'image'=>'upload/sushi-5.jpg',
        'rating'=> '3.5 Buono (320)',
    ]
]
?>