<?php return[
    [
        'image'=>'upload/pizza-9.jpg',
        'name'=>'Pizzeria'
    ],[
        'image'=>'upload/sushi-11.jpg',
        'name'=>'Sushi'
    ],[
        'image'=>'upload/meat-5.jpg',
        'name'=>'Carne'
    ],[
        'image'=>'upload/hamburger-14.jpg',
        'name'=>'Burger'
    ],[
        'image'=>'upload/dessert-7.jpg',
        'name'=>'Dessert'
    ],[
        'image'=>'upload/italiano.jpg',
        'name'=>'Italiano'
    ],
]?>