<?php
return[
    [
       'name'=>'Antonino',  
       'surname'=>'Canavacciuolo',  
       'vat_number'=>'01234568919',  
       'email'=>'antonio.canavacciulo@deliveboo.it',  
       'password'=>'password',  
    ],
    [
        'name'=>'Bruno',  
        'surname'=>'Barbieri',  
        'vat_number'=>'01234537819',  
        'email'=>'bruno.barbieri@deliveboo.it',  
        'password'=>'password',  
     ],
     [
        'name'=>'Carlo',  
        'surname'=>'Cracco',  
        'vat_number'=>'01234538939',  
        'email'=>'carlo.cracco@deliveboo.it',  
        'password'=>'password',  
     ],[
        'name'=>'Alessandro',  
        'surname'=>'Borghesi',  
        'vat_number'=>'01232537819',  
        'email'=>'alessandro.borghesi@deliveboo.it',  
        'password'=>'password',  
     ],[
        'name'=>'Massimo',  
        'surname'=>'Bottura',  
        'vat_number'=>'01434537891',  
        'email'=>'massimo.bottura@deliveboo.it',  
        'password'=>'password',  
     ],[
        'name'=>'Gianfranco',  
        'surname'=>'Vissani',  
        'vat_number'=>'012345378919',  
        'email'=>'gianfranco.vissani@deliveboo.it',  
        'password'=>'password',  
     ],[
        'name'=>'Xin',  
        'surname'=>'Zhao',  
        'vat_number'=>'012345378919',  
        'email'=>'xin.zhao@deliveboo.it',  
        'password'=>'password',
     ],[
      'name'=>'Chin',  
      'surname'=>'Bhan',  
      'vat_number'=>'012335378919',  
      'email'=>'chin.bhan@deliveboo.it',  
      'password'=>'password',
      ],[
         'name'=>'Mario',  
         'surname'=>'Ottani',  
         'vat_number'=>'012245378919',  
         'email'=>'mario.ottani@deliveboo.it',  
         'password'=>'password',
      ],[
         'name'=>'Chin',  
         'surname'=>'Chan',  
         'vat_number'=>'012245378959',  
         'email'=>'chin.chan@deliveboo.it',  
         'password'=>'password',
      ]

]
?>