<?php
return[
    [
       'name'=>'Marco',  
       'surname'=>'Rossi',  
       'vat_number'=>'63748291033',  
       'email'=>'marco.rossi@deliveboo.it',  
       'password'=>'password',  
    ],
    [
        'name'=>'Sara',  
        'surname'=>'Ferrari',  
        'vat_number'=>'84920381765',  
        'email'=>'sara.ferrari@deliveboo.it',  
        'password'=>'password',  
     ],
     [
        'name'=>'Alessandro',  
        'surname'=>'Esposito',  
        'vat_number'=>'56291043827',  
        'email'=>'alessandro.esposito@deliveboo.it',  
        'password'=>'password',  
     ],[
        'name'=>'Giulia',  
        'surname'=>'Ricci',  
        'vat_number'=>'38471926450',  
        'email'=>'giulia.ricci@deliveboo.it',  
        'password'=>'password',  
     ],[
        'name'=>'Francesco',  
        'surname'=>'Romano',  
        'vat_number'=>'92750164833',  
        'email'=>'francesco.romano@deliveboo.it',  
        'password'=>'password',  
     ],[
        'name'=>'Martina',  
        'surname'=>'Conti',  
        'vat_number'=>'15678492037',  
        'email'=>'martina.conti@deliveboo.it',  
        'password'=>'password',  
     ],[
        'name'=>'Luca',  
        'surname'=>'Marino',  
        'vat_number'=>'32897561049',  
        'email'=>'luca.marino@deliveboo.it',  
        'password'=>'password',
     ],[
      'name'=>'Chiara',  
      'surname'=>'Greco',  
      'vat_number'=>'41589273608',  
      'email'=>'chiara.greco@deliveboo.it',  
      'password'=>'password',
      ],[
         'name'=>'Matteo',  
         'surname'=>'Lombardi',  
         'vat_number'=>'76301948257',  
         'email'=>'matteo.lombardi@deliveboo.it',  
         'password'=>'password',
      ],[
         'name'=>'Valentina',  
         'surname'=>'Rizzo',  
         'vat_number'=>'29106438572',  
         'email'=>'valentina.rizzo@deliveboo.it',  
         'password'=>'password',
      ],[
         'name'=>'Akira',  
         'surname'=>'Kim',  
         'vat_number'=>'50816392745',  
         'email'=>'akira.kim@deliveboo.it',  
         'password'=>'password',
      ],[
         'name'=>'Haruki',  
         'surname'=>'Lee',  
         'vat_number'=>'01234567891',  
         'email'=>'haruki.lee@deliveboo.it',  
         'password'=>'password',
      ],[
         'name'=>'Hiroshi',  
         'surname'=>'Chen',  
         'vat_number'=>'01234567892',  
         'email'=>'hiroshi.chen@deliveboo.it',  
         'password'=>'password',
      ],[
         'name'=>'Mei',  
         'surname'=>'Tanaka',  
         'vat_number'=>'01234567893',  
         'email'=>'mei.tanaka@deliveboo.it',  
         'password'=>'password',
      ],[
         'name'=>'Sakura',  
         'surname'=>'Wong',  
         'vat_number'=>'01234567894',  
         'email'=>'sakura.wong@deliveboo.it',  
         'password'=>'password',
      ],[
         'name'=>'Xia',  
         'surname'=>'Gupta',  
         'vat_number'=>'01234567895',  
         'email'=>'xia.gupta@deliveboo.it',  
         'password'=>'password',
      ],[
         'name'=>'Min-Jae',  
         'surname'=>'Singh',  
         'vat_number'=>'01234567896',  
         'email'=>'minjae.singh@deliveboo.it',  
         'password'=>'password',
      ],[
         'name'=>'Mei-Ling',  
         'surname'=>'Nguyen',  
         'vat_number'=>'01234567897',  
         'email'=>'meiling.nguyen@deliveboo.it',  
         'password'=>'password',
      ]

]
?>